# Generated by Django 3.2.4 on 2024-11-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220103_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content_image',
            field=models.ImageField(blank=True, upload_to='content_images/'),
        ),
    ]
